// Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0
// Build dist/augmentor-browser.mjs: one self-contained ES module for apps without a bundler.
// Each source module keeps its own scope; only the SDK's own simple export syntax is supported.
import {readFileSync, writeFileSync, mkdirSync} from 'node:fs';
import {dirname, resolve, relative, sep} from 'node:path';
import {fileURLToPath} from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const entry = resolve(root, 'src/browser.mjs');
const modules = new Map(); const order = [];

function load(file) {
  if (modules.has(file)) return modules.get(file);
  // Git on Windows may check sources out with CRLF; the bundle is always built with LF.
  const source = readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
  const info = {file, id: '__m' + modules.size, imports: [], exports: [], reexports: [], body: source};
  modules.set(file, info);
  info.body = info.body.replace(/^import\s*\{([^}]*)\}\s*from\s*'(\.[^']+)';\s*$/gm, (_, names, spec) => {
    const target = load(resolve(dirname(file), spec)); info.imports.push(target);
    return `const {${names.replace(/\s+as\s+/g, ': ')}} = ${target.id};`;
  });
  info.body = info.body.replace(/^export\s*\{([^}]*)\}\s*from\s*'(\.[^']+)';\s*$/gm, (_, names, spec) => {
    const target = load(resolve(dirname(file), spec)); info.imports.push(target);
    for (const name of names.split(',').map(s => s.trim()).filter(Boolean)) info.reexports.push({name, from: target.id});
    return '';
  });
  if (/^import\s/m.test(info.body)) throw Error(`${relative(root, file)} has an import the browser bundler does not support`);
  info.body = info.body.replace(/^export\s+(async\s+function|function|const|let|class)\s+([A-Za-z_$][\w$]*)/gm, (_, kind, name) => {info.exports.push(name); return `${kind} ${name}`;});
  if (/^export\s/m.test(info.body)) throw Error(`${relative(root, file)} uses an export form the browser bundler does not support`);
  order.push(info);
  return info;
}

load(entry);
const header = `// Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0
// @augmentor/app-sdk browser bundle ${JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8')).version}. Generated by scripts/build-browser.mjs; do not edit.
`;
// Forward slashes keep the bundle byte-identical on Windows.
const posix = file => relative(root, file).split(sep).join('/');
const parts = order.filter(m => m.file !== entry).map(m => `// ${posix(m.file)}\nconst ${m.id} = (() => {\n${m.body.replace(/^\/\/ Copyright.*\n/m, '')}\nreturn {${m.exports.join(', ')}};\n})();`);
const top = modules.get(entry);
const exported = top.reexports.map(r => `export const ${r.name} = ${r.from}.${r.name};`);
const output = header + parts.join('\n\n') + '\n\n' + exported.join('\n') + '\n';
const target = resolve(root, 'dist/augmentor-browser.mjs');
if (process.argv.includes('--check')) {
  const current = (() => {try {return readFileSync(target, 'utf8').replace(/\r\n/g, '\n');} catch {return '';}})();
  if (current !== output) {console.error('dist/augmentor-browser.mjs is out of date; run npm run build'); process.exit(1);}
  console.log('Browser bundle is up to date');
} else {
  mkdirSync(dirname(target), {recursive: true}); writeFileSync(target, output);
  console.log(`Wrote ${relative(root, target)} (${order.length} modules, ${output.length} bytes)`);
}
