// Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: LicenseRef-Augmentor-MIT-Resale-1.0
import {createRequire} from 'node:module';
import {realpathSync,readFileSync} from 'node:fs';
import {pathToFileURL,fileURLToPath} from 'node:url';
import {createApplicationTools,createToolClient} from './tools.mjs';
import {toDshParameters} from './dsh-schema.mjs';
export {createToolClient} from './tools.mjs';
export async function registerDshTools(ctx,{definitions,execute,defineTool:factory}) {
  if(!factory){
    // DSH resolves plugins from its own entry point; fall back to this module for embedded or REPL use.
    const base=process.argv[1]?realpathSync(process.argv[1]):fileURLToPath(import.meta.url);
    const require=createRequire(base);factory=(await import(pathToFileURL(require.resolve('@deepseek-ai/dsh-tools')).href)).defineTool;}
  const application=createApplicationTools({definitions,execute});
  const schemas=new Map(application.tools.map(tool=>[tool.name,tool.inputSchema]));
  for(const [name,description] of definitions){
    // DSH accepts a stricter descriptor DSL than JSON Schema; the SDK still validates the full schema.
    ctx.tools.register(factory({name,description,parameters:toDshParameters(schemas.get(name)),output:{schema:{type:'string'},render:(_args,value)=>[{type:'text',text:value}]},
      async execute(args,execution){return JSON.stringify(await application.execute(name,args,execution));}
    }));
  }
  // The Augmentor preset owns presentation. DSH rejects a second declaration,
  // including an identical mode, in the same composition.
}

/**
 * Build the tool module the Augmentor runtime loads (augmentor/tools.mjs). It reads the
 * static descriptors generated by `augmentor-app manifest` (tools.json) and forwards calls
 * to the application's endpoint; no application code runs inside the agent runtime.
 *   export const {name, inject, apply, applicationTools} = createToolModule({pluginId, descriptors: new URL('./tools.json', import.meta.url)});
 */
export function createToolModule({pluginId, descriptors}) {
  if(!/^[a-z][a-z0-9-]{0,63}$/.test(pluginId||''))throw Object.assign(Error('createToolModule needs the manifest plugin ID'),{code:'INVALID_TOOL'});
  const load=()=>{
    let value;
    try{value=typeof descriptors==='object'&&!(descriptors instanceof URL)?descriptors:JSON.parse(readFileSync(descriptors,'utf8'));}
    catch{throw Object.assign(Error('Tool descriptors are missing or invalid; run augmentor-app manifest'),{code:'INVALID_TOOL'});}
    if(value?.schemaVersion!==1||!Array.isArray(value.tools))throw Object.assign(Error('Unsupported tool descriptor file'),{code:'INVALID_TOOL'});
    return value.tools.map(t=>[t.name,t.description,t.inputSchema,...(t.outputSchema?[t.outputSchema]:[])]);
  };
  const executor=config=>createToolClient({url:config.url,tokenFile:config.tokenFile,...(config.timeoutMs?{timeoutMs:config.timeoutMs}:{})});
  return {
    name:pluginId,
    inject:['tools'],
    async apply(ctx,config){await registerDshTools(ctx,{definitions:load(),execute:executor(config)});},
    applicationTools(config){return createApplicationTools({definitions:load(),execute:executor(config)});},
  };
}
